-- 
-- Inserir generos
-- 

INSERT INTO genero (nome) VALUES
--('latin'),
--('latin pop'),
('dwn trap'),
('pop rap'),
('rap'),
('trap music'),
('hip hop'),
('west coast rap'),
('electro house'),
('house'),
('pop'),
('progressive house'),
('canadian pop'),
('southern hip hop'),
('modern rock'),
('vegas indie'),
('contemporary country'),
('dance pop'),
('edm'),
('tropical house'),
('complextro'),
('german techno'),
('post-teen pop'),
('viral pop'),
('etherpop'),
('indie poptimism'),
('big room'),
('gangster rap'),
('indie r&b'),
('underground hip hop'),
('pop christmas'),
('detroit hip hop'),
('minimal dub'),
('moombahton'),
('deep indie r&b'),
('r&b'),
('country'),
('country road'),
('modern country rock'),
('talent show'),
('reggaeton'),
('dirty south rap'),
('deep big room'),
('teen pop'),
('metropopolis'),
('neo mellow'),
('piano rock'),
('pop rock'),
('latin hip hop'),
('tropical'),
('redneck'),
('uk funky'),
('indie pop'),
('indie rock'),
('indietronica'),
('neo-psychedelic'),
('boy band'),
('urban contemporary'),
('soul christmas'),
('stomp and holler'),
('pop punk'),
('chamber pop'),
('folk-pop'),
('indie folk'),
('new americana'),
('hollywood'),
('australian country'),
('country christmas'),
('crunk'),
('deep trap'),
('memphis hip hop'),
('grime'),
('deep groove house'),
('disco house'),
('filter house'),
('vocal house'),
('europop'),
('alternative rock'),
('britpop'),
('permanent wave'),
('rock'),
('destroy techno'),
('indie christmas'),
('hip pop'),
('new jack swing'),
('garage rock'),
('sheffield indie'),
('liquid funk'),
('afrobeats'),
('azonto'),
('azontobeats'),
('alternative dance'),
('irish rock'),
('new rave'),
('deep tropical house'),
('electronic trap'),
('candy pop'),
('emo'),
('pop emo'),
('blues-rock'),
('classic rock'),
('punk blues'),
('la indie'),
('neo-singer-songwriter'),
('singer-songwriter'),
('swedish pop'),
('chanson'),
('dancehall'),
('reggae fusion'),
('classic funk rock'),
('disco'),
('funk'),
('funk rock'),
('jazz funk'),
('motown'),
('quiet storm'),
('soul'),
('progressive electro house'),
('g funk'),
('trap latino'),
('deep funk carioca'),
('reggaeton flow'),
('pop reggaeton'),
('cumbia pop'),
('riddim'),
('latin christmas'),
('electro latino'),
('cumbia villera'),
('bachata'),
('merengue urbano'),
('vallenato'),
('spanish pop'),
('argentine rock'),
('folklore argentino'),
('rock en espanol'),
('latin alternative'),
('cubaton'),
('grupera'),
('mariachi'),
('ranchera'),
('australian dance'),
('deep euro house'),
('deep german pop rock'),
('deep german hip hop'),
('german hip hop'),
('german pop'),
('german pop rock'),
('modern blues'),
('deep underground hip hop'),
('underground pop rap'),
('austropop'),
('german indie'),
('vienna indie'),
('minimal tech house'),
('eurovision'),
('swedish idol pop'),
('hands up'),
('italo dance'),
('channel pop'),
('album rock'),
('hard rock'),
('mellow gold'),
('soft rock'),
('danish pop'),
('deep danish pop'),
('alternative metal'),
('nu metal'),
('post-grunge'),
('rap metal'),
('norwegian indie'),
('bass trap'),
('catstep'),
('melbourne bounce'),
('deep australian indie'),
('indie anthem-folk'),
('australian hip hop'),
('aussietronica'),
('australian alternative rock'),
('downtempo'),
('dance-punk'),
('acoustic pop'),
('vapor soul'),
('electronic'),
('neo soul'),
('heavy christmas'),
('punk christmas'),
('deep dutch hip hop'),
('dutch hip hop'),
('soundtrack'),
('trap francais'),
('bubble trance'),
('bubblegum dance'),
('eurodance'),
('dutch pop'),
('belgian rock'),
('francoton'),
('canadian indie'),
('progressive trance'),
('trance'),
('chalga'),
('sertanejo universitario'),
('forro'),
('pagode'),
('sertanejo'),
('brazilian hip hop'),
('axe'),
('brostep'),
('east coast hip hop'),
('chilean rock'),
('nueva cancion'),
('salsa'),
('colombian rock'),
('cumbia'),
('argentine reggae'),
('glam metal'),
('lovers rock'),
('roots reggae'),
('spanish pop rock'),
('glam rock'),
('czech hip hop'),
('czech folk'),
('czech rock'),
('slovak pop'),
('slovak hip hop'),
('grunge'),
('adult standards'),
('dance rock'),
('folk rock'),
('new wave pop'),
('schlager'),
('french hip hop'),
('discofox'),
('pop house'),
('deep pop edm'),
('danish hip hop'),
('merengue'),
('cantautor'),
('spanish rock'),
('finnish dance pop'),
('finnish hip hop'),
('finnish pop'),
('suomi rock'),
('tracestep'),
('french indie pop'),
('japanese r&b'),
('post-disco'),
('french pop'),
('electrofox'),
('french indietronica'),
('french rock'),
('entehno'),
('laiko'),
('regional mexican'),
('regional mexican pop'),
('banda'),
('norteno'),
('k-pop'),
('c-pop'),
('cantopop'),
('deep taiwanese pop'),
('mandopop'),
('taiwanese pop'),
('k-hop'),
('korean pop'),
('alternative r&b'),
('singaporean pop'),
('shiver pop'),
('hungarian hip hop'),
('hungarian pop'),
('hungarian rock'),
('indonesian pop'),
('world worship'),
('dangdut'),
('indonesian indie'),
('norwegian metal'),
('celtic rock'),
('celtic christmas'),
('british blues'),
('funk metal'),
('uk garage'),
('classic icelandic pop'),
('icelandic pop'),
('italian hip hop'),
('italian arena pop'),
('italian pop'),
('italian pop rock'),
('relaxative'),
('denver indie'),
('sky room'),
('anime'),
('j-pop'),
('j-rock'),
('j-rap'),
('j-metal'),
('otacore'),
('j-dance'),
('japanese city pop'),
('j-idol'),
('j-indie'),
('japanese jazztronica'),
('shibuya-kei'),
('j-poprock'),
('melancholia'),
('future funk'),
('latvian pop'),
('deep regional mexican'),
('bolero'),
('deep latin hip hop'),
('world christmas'),
('malaysian pop'),
('rap rock'),
('australian pop'),
('dutch house'),
('carnaval'),
('levenslied'),
('dutch rock'),
('deep swedish hip hop'),
('russelater'),
('norwegian hip hop'),
('norwegian pop'),
('classic norwegian pop'),
('nordic house'),
('danseband'),
('norwegian rock'),
('swedish synthpop'),
('country rock'),
('folk christmas'),
('roots rock'),
('deep pop r&b'),
('latin electronica'),
('nu-cumbia'),
('opm'),
('pinoy alternative'),
('minimal techno'),
('tech house'),
('deep neofolk'),
('show tunes'),
('lilith'),
('idol'),
('polish hip hop'),
('polish pop'),
('portuguese rock'),
('hip hop tuga'),
('kizomba'),
('semba'),
('baile funk'),
('danspunk'),
('swedish eurodance'),
('swedish hip hop'),
('swedish folk pop'),
('classic swedish pop'),
('swedish indie rock'),
('melodipop'),
('deep swedish indie pop'),
('swedish alternative rock'),
('swedish indie pop'),
('turkish pop'),
('groove room'),
('turkish rock'),
('deep turkish pop'),
('arabesk'),
('turkish hip hop'),
('turkish folk'),
('turkish jazz'),
('classical piano'),
('classic chinese pop'),
('medieval');

